import { filmImages } from "./FilmImages";
import reactLogo from "../img/react.svg";
import { GrFormView } from "react-icons/gr";
import { FaComments } from "react-icons/fa";
import { FaHeart } from "react-icons/fa";

const FilmList = [
  {
    id: crypto.randomUUID(),
    img: null,
    link: "https://vider.info/vid/+f8mcs8c",
    bg: filmImages["Spider-Man"],
    img_vive: GrFormView,
    vive: 3000,
    img_dm: FaComments,
    dm: 1200,
    img_likes: FaHeart,
    likes: 2500,
    title: "Spider‑Man",
    creator: "Sam Raimi",
    releaseDate: "2002-05-03",
  },
  {
    id: crypto.randomUUID(),
    img: null,
    link: "https://vider.info/vid/+fs8v8xe",
    bg: filmImages["The Batman"],
    img_vive: GrFormView,
    vive: 500,
    img_dm: FaComments,
    dm: 300,
    img_likes: FaHeart,
    likes: 2000,
    title: "The Batman",
    creator: "Matt Reeves",
    releaseDate: "2022-03-04",
  },
  {
    id: crypto.randomUUID(),
    img: null,
    link: "https://www.cda.pl/video/15596997c1",
    bg: filmImages.Deadpool,
    img_vive: GrFormView,
    vive: 16500,
    img_dm: FaComments,
    dm: 700,
    img_likes: FaHeart,
    likes: 20970,
    title: "Deadpool",
    creator: "Tim Miller",
    releaseDate: "2016-02-12",
  },
  {
    id: crypto.randomUUID(),
    img: null,
    link: "https://vider.info/vid/+fxnsn5s",
    bg: filmImages.Inception,
    img_vive: GrFormView,
    vive: 300,
    img_dm: FaComments,
    dm: 500,
    img_likes: FaHeart,
    likes: 3000,
    title: "Inception",
    creator: "Christopher Nolan",
    releaseDate: "2010-07-16",
  },
  {
    id: crypto.randomUUID(),
    img: null,
    link: "https://www.cda.pl/video/71823821d",
    bg: filmImages["Iron Man"],
    img_vive: GrFormView,
    vive: 2000,
    img_dm: FaComments,
    dm: 800,
    img_likes: FaHeart,
    likes: 400,
    title: "Iron Man",
    creator: "Jon Favreau",
    releaseDate: "2008-05-02",
  },
  {
    id: crypto.randomUUID(),
    img: null,
    link: "https://pl.vider-info.pl/ca%C5%82y-film/60000-Avengers:-Koniec-gry-PL-online.html",
    bg: filmImages["Avengers: Endgame"],
    img_vive: GrFormView,
    vive: 6789,
    img_dm: FaComments,
    dm: 1012,
    img_likes: FaHeart,
    likes: 8901,
    title: "Avengers: Endgame",
    creator: "Russo Brothers",
    releaseDate: "2019-04-26",
  },
  {
    id: crypto.randomUUID(),
    img: null,
    link: "https://vider.info/vid/+fx5xm85",
    bg: filmImages.Joker,
    img_vive: GrFormView,
    vive: 7890,
    img_dm: FaComments,
    dm: 2123,
    img_likes: FaHeart,
    likes: 9012,
    title: "Joker",
    creator: "Todd Phillips",
    releaseDate: "2019-10-04",
  },
  {
    id: crypto.randomUUID(),
    img: null,
    link: "https://vider.info/vid/+fexsvmc",
    bg: filmImages.Interstellar,
    img_vive: GrFormView,
    vive: 8901,
    img_dm: FaComments,
    dm: 5234,
    img_likes: FaHeart,
    likes: 1234,
    title: "Interstellar",
    creator: "Christopher Nolan",
    releaseDate: "2014-11-07",
  },
  {
    id: crypto.randomUUID(),
    img: null,
    link: "https://www.cda.pl/video/2096912762",
    bg: filmImages.Matrix,
    img_vive: GrFormView,
    vive: 9012,
    img_dm: FaComments,
    dm: 2345,
    img_likes: FaHeart,
    likes: 2345,
    title: "Matrix 3",
    creator: "Wachowscy",
    releaseDate: "2003-11-05",
  },
  {
    id: crypto.randomUUID(),
    img: null,
    link: "https://www.cda.pl/video/23710962e0/vfilm",
    bg: filmImages.Gladiator,
    img_vive: GrFormView,
    vive: 10123,
    img_dm: FaComments,
    dm: 1156,
    img_likes: FaHeart,
    likes: 3456,
    title: "Gladiator",
    creator: "Ridley Scott",
    releaseDate: "2000-05-05",
  },
  {
    id: crypto.randomUUID(),
    img: null,
    link: "https://www.cda.pl/video/22570886e9/vfilm",
    bg: filmImages["Fight Club"],
    img_vive: GrFormView,
    vive: 11234,
    img_dm: FaComments,
    dm: 1467,
    img_likes: FaHeart,
    likes: 4567,
    title: "Fight Club",
    creator: "David Fincher",
    releaseDate: "1999-10-15",
  },
  {
    id: crypto.randomUUID(),
    img: null,
    link: "https://vider.info/vid/+fvnmnm",
    bg: filmImages["Mad Max: Fury Road"],
    img_vive: GrFormView,
    vive: 12345,
    img_dm: FaComments,
    dm: 3678,
    img_likes: FaHeart,
    likes: 5678,
    title: "Mad Max: Fury Road",
    creator: "George Miller",
    releaseDate: "2015-05-15",
  },
  {
    id: crypto.randomUUID(),
    img: null,
    link: "https://pl.vider-info.pl/ca%C5%82y-film/57568-Guardians-of-the-Galaxy-Vol-3-online.html",
    bg: filmImages["Guardians of the Galaxy"],
    img_vive: GrFormView,
    vive: 13456,
    img_dm: FaComments,
    dm: 2789,
    img_likes: FaHeart,
    likes: 6789,
    title: "Guardians of the Galaxy 3",
    creator: "James Gunn",
    releaseDate: "2023-05-05",
  },
  {
    id: crypto.randomUUID(),
    img: null,
    link: "https://www.cda.pl/video/240062822e/vfilm",
    bg: filmImages["John Wick"],
    img_vive: GrFormView,
    vive: 17456,
    img_dm: FaComments,
    dm: 2589,
    img_likes: FaHeart,
    likes: 15789,
    title: "John Wick",
    creator: "Chad Stahelski",
    releaseDate: "2014-10-24",
  },
  {
    id: crypto.randomUUID(),
    img: null,
    link: "https://vider.info/vid/+fe1m8n5",
    bg: filmImages["Doctor Strange"],
    img_vive: GrFormView,
    vive: 1456,
    img_dm: FaComments,
    dm: 2089,
    img_likes: FaHeart,
    likes: 6389,
    title: "Doctor Strange",
    creator: "Scott Derrickson",
    releaseDate: "2016-11-04",
  },
];

export default FilmList;
